N_ACTIONS = 6
N_DICES = 6
N_DICE_FACES = 6
N_DICE_TYPES = 2
N_MAX_FACE_VALUE = 20
N_MIN_FACE_VALUE = 1
N_MAX_ROLLS = 3

MAX_ROLL = N_DICES * N_MAX_FACE_VALUE / 2
MIN_ROLL = N_DICES * N_MIN_FACE_VALUE / 2

MIN_PLAYER_HP = 100
MAX_PLAYER_HP = 100

MIN_ENEMY_HP = 100
MAX_ENEMY_HP = 200
MAX_ENEMY_ATTACK = 50
MIN_ENEMY_ATTACK = 10
MAX_ENEMY_DEFENSE = 50
MIN_ENEMY_DEFENSE = 10

N_TRAITS = 4

WIN_REWARD = 10000
LOSE_REWARD = -10000
DAMAGE_REWARD_MULTIPLIER = 100
